sudo: required
services:
  - docker

before_install:
  - docker build -t cpeterson15/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true USERNAME/docker-react npm run test -- --coverage
